name: Sync to GitCode

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Pull changes
        run: |
          git fetch origin
          git merge origin/main --ff-only || git merge origin/main  
      - name: Set up Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Push to GitCode
        run: |
          # 使用 HTTPS 推送（需 GitCode 账号 token）
          echo "gitcode token ${{ secrets.GITHUB_TOKEN }}"
          git remote add gitcode https://strawberrycake:jc7ig54qtnqH4ZjNmT42vFgs@gitcode.com/strawberrycake/test.git
          git push gitcode main
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
